name: Build plugin

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_windows:
    strategy:
      matrix:
        arch: [x64, Win32]

    name: Build plugin for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build plugin
        run: |
          cmake  -G "Visual Studio 18 2026" -A ${{ matrix.arch }} .
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: rotate-windows-${{ matrix.arch }}
          path: rotate.dll

  build_linux:
    name: Build plugin for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build plugin
        run: |
          cmake -G Ninja .
          ninja

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: rotate-linux
          path: rotate.so
