name: Build plugin

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        arch: [x64, x86]
        exclude:
          - os: ubuntu
            arch: x86

    name: Build plugin
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build Plugin
        run: |
          cmake -A ${{ matrix.arch }} -G Ninja .
          ninja

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: rotate-${{ matrix.os }}-${{ matrix.arch }}
          path: rotate.*
