name: Build DLLs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build_windows_x64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build Plugin
        run: |
          cmake -G "NMake Makefiles" .
          nmake

      - uses: actions/upload-artifact@v2
        with:
          name: rotate-x64
          path: rotate.dll

  build_windows_x86:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build Plugin
        run: |
          cmake -G "NMake Makefiles" .
          nmake

      - uses: actions/upload-artifact@v2
        with:
          name: rotate-x86
          path: rotate.dll

  release:
    runs-on: ubuntu-latest
    needs: [build_windows_x64, build_windows_x86]

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R
